[package]
name = "sweetrpg-kv-objects"
description = "Objects for the SweetRPG Key-value Store."
homepage = "https://sweetrpg-kv-objects.github.com/"
authors = ["Paul Schifferer <paul@schifferers.net>"]
documentation = "https://sweetrpg-kv-objects.github.com/"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/sweetrpg/kv-objects/"
version = "0.0.1"
rust-version = "1.72.1"
edition = "2021"

exclude = [
    ".github/*",
    "scripts/*",
    "coverage.svg",
    ".editorconfig",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
