name: Python CI

on:
    push:
        branches: [python]
        paths:
            - "src/**"
            - "tests/**"
            - setup.cfg
            - setup.py
            - tox.ini
            - "requirements/*.txt"
            - "docs/**"
    workflow_run:
        workflows: ["Update Requirements"]
        types: [completed]

jobs:
    build:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        concurrency: python-ci
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          python: "3.11",
                          os: ubuntu-latest,
                          tox: py311,
                      }
                    # - { name: Windows, python: "3.10", os: windows-latest, tox: py310 }
                    # - { name: Mac, python: "3.10", os: macos-latest, tox: py310 }
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - name: update-pip
              run: |
                  pip install -U wheel setuptools
                  python -m pip install -U pip
            - name: get-pip-cache-dir
              id: pip-cache
              run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
            - name: cache-pip
              uses: actions/cache@v3
              with:
                  path: ${{ steps.pip-cache.outputs.dir }}
                  key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('setup.py') }}|${{ hashFiles('requirements/*.txt') }}
            - name: install-utils
              run: pip install tox
            - name: tests
              run: |
                  tox -e ${{ matrix.tox }}

    docs:
        needs: [build]
        runs-on: ubuntu-latest
        concurrency: python-docs
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: install-deps
              run: pip install -r requirements/docs.txt
            - name: make-docs
              run: cd docs && make html
            - name: publish-docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/_build/html

    publish:
        needs: [build]
        runs-on: ubuntu-latest
        concurrency: python-publish
        permissions:
            id-token: write
            contents: write
        environment:
            name: release
            url: https://pypi.org/p/sweetrpg-kv-objects
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Release
              id: release
              uses: python-semantic-release/python-semantic-release@v9.8.8
              with:
                  force: "patch"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              if: steps.release.outputs.released == 'true'
              with:
                  packages-dir: ./
                  skip-existing: true
                  verbose: true
                  password: ${{ secrets.PYPI_TOKEN }}
            - name: Publish package distributions to GitHub Releases
              uses: python-semantic-release/upload-to-gh-release@v9.8.8
              if: steps.release.outputs.released == 'true'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

    notify:
        needs: [publish]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - repo: kv-api
                    - repo: client
                    - repo: main-web
                    - repo: shared-web
                    - repo: web-core
                    - repo: kv-expression-processor
                    - repo: kv-key-processor
                    - repo: kv-value-calculator
        steps:
            - name: Notify
              uses: juztcode/repo-ditpatch-action@v1
              with:
                  event-type: kv-objects-published
                  token: ${{ secrets.REPO_ACCESS_TOKEN }}
                  repository: sweetrpg/${{ matrix.repo }}
#            - name: dispatch-event
#              uses: ph-fritsche/action-dispatch@v1
#              with:
#                token: ${{ secrets.GITHUB_TOKEN }}
#                type: repository
#                ident: published
#                payload: '{"foo":"bar"}' # json
