name: PR

on:
    pull_request:
        branches: [rust]
        paths:
            - "src/**"
            - "tests/**"
            - "benches/**"
            - "examples/**"

jobs:
    tests:
        name: Linux
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                toolchain:
                    - stable
                    - beta
                    - nightly
        steps:
            - uses: actions/checkout@v3
            - name: install-toolchain
              run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - name: build
              run: cargo build --verbose
            - name: lint
              run: cargo check --verbose
            - name: tests
              run: cargo test --verbose
            - name: coverage
              uses: paambaati/codeclimate-action@v5.0.0
              env:
                CC_TEST_REPORTER_ID: 5e973b60767b2306b570ae43a2690cd0352801d8b6a0af5eb1b777672c5bab0a
