name: PR

on:
    pull_request:
        branches: [rust]
        paths:
            - "src/**"
            - "docs/**"

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          rust: "1.73.0",
                          os: ubuntu-latest,
                      }
        steps:
            - uses: actions/checkout@v3
            - name: install-utils
              run: echo "hello"
            - name: lint
              run: cargo fmt
            - name: tests
              run: cargo test
            - name: coverage
              uses: paambaati/codeclimate-action@v5.0.0
              env:
                CC_TEST_REPORTER_ID: 5e973b60767b2306b570ae43a2690cd0352801d8b6a0af5eb1b777672c5bab0a
