name: CI

on:
    push:
        branches: [rust]
        paths:
            - "src/**"
            - "tests/**"
            - Cargo.toml
            - "docs/**"
    workflow_run:
        workflows: ["Update Requirements"]
        types: [completed]

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        concurrency: ci
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          rust: "1.73.0",
                          os: ubuntu-latest,
                      }
        steps:
            - uses: actions/checkout@v3
            - name: install-utils
              run: echo "hello"
            - name: tests
              run: |
                  cargo test

    docs:
        needs: [tests]
        runs-on: ubuntu-latest
        concurrency: docs
        steps:
            - uses: actions/checkout@v2
            - name: make-docs
              run: cd docs && make html
            - name: publish-docs
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs/_build/html

    publish:
        needs: [tests]
        runs-on: ubuntu-latest
        concurrency: publish
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            # - name: Publish
            #   uses: relekang/python-semantic-release@v7.34.6
            #   with:
            #       additional_options: "--patch"
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       repository_username: __token__
            #       repository_password: ${{ secrets.PYPI_TOKEN }}

    notify:
        needs: [publish]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - repo: kv-api
                    - repo: client
                    - repo: main-web
                    - repo: shared-web
                    - repo: web-core
                    - repo: kv-expression-processor
                    - repo: kv-key-processor
                    - repo: kv-value-calculator
        steps:
            - name: Notify
              uses: juztcode/repo-ditpatch-action@v1
              with:
                  event-type: kv-objects-published
                  token: ${{ secrets.REPO_ACCESS_TOKEN }}
                  repository: sweetrpg/${{ matrix.repo }}
#            - name: dispatch-event
#              uses: ph-fritsche/action-dispatch@v1
#              with:
#                token: ${{ secrets.GITHUB_TOKEN }}
#                type: repository
#                ident: published
#                payload: '{"foo":"bar"}' # json
